baseURL: "feliperomagna.net" 
title: Felipe Romagna
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Works
          url: works/
          weight: 5 
        - name: Papers
          url: papers/
          weight: 4 
        - name: Blog
          url: archive/
          weight: 6
        - name: About
          url: about/
        - name: Welcome
          url: welcome/
          weight: 1
params:
    description: "This website hosts Felipe Romagna's research papers, books, course materials, data, curriculum vitae, and contact information."
    author: Felipe Romagna
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: false
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers","works"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: true
    math: true
    profileMode:
          enabled: true
          title: Felipe Romagna
          subtitle: "Sou músico, professor e pesquisador. Este espaço funciona como um repositório de trabalhos, pesquisas e também de textos que gosto de compartilhar a respeito de diversos assuntos. <br> *I'm a musician, teacher, and researcher. This space serves as a repository for my work, research, and also texts I like to share on various topics*"
          # imageUrl: "picture.jpg"
          # imageWidth: 160
          # imageHeight: 160
          buttons:
            - name: "Welcome"
              url: welcome/
            - name: Works
              url: works/
            - name: Papers
              url: papers/
            - name: Blog
              url: archive/
            - name: About
              url: about/


    socialIcons:
        - name: Bluesky
          url: https://bsky.app/profile/feliperomagna.net
        - name: Mastodon
          url: https://mastodon.social/@feliperomagna
        - name: Instagram
          url: https://www.instagram.com/feliperomagna/
        - name: Email
          url: mailto:liperomagna47@hotmail.com
        - name: GitHub
          url: https://github.com/feliperomagna
        - name: Substack
          url: https://substack.com/@feliperomagna?r=5ks8nz&utm_medium=ios&utm_source=profile
        - name: YouTube
          url: https://www.youtube.com/@FelipeRomagna

        
    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Felipe Romagna"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2