baseURL: "www.feliperomagna.github.io" 
title: Felipe Romagna
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Works
          url: works/
          weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 
        - name: Blog
          url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
          weight: 6

params:
    description: "This website hosts Moritz-Maria von Igelfeld's research papers, books, course materials, data, curriculum vitae, and contact information."
    author: Moritz-Maria von Igelfeld
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Professor Dr von Igelfeld
          subtitle: "Atualmente, em 2025, sou doutorando em Música pela UFMG. Minha pesquisa envolve uma ideia de apropriação técno-poética de ferramentas de IA para a criação musical. Tenho produzido alguns trabalhos artísticos que podem ser conferidos na seção [Works]{% link works.markdown %}. Também tenho mestrado em Comunicação audiovisual pela Universidade Anhembi Morumbi, efetuando uma pesquisa de resgate do filme "Cidade Mulher (1936)" produzido pelo Humberto Mauro e Carmen Santos, e com trilha sonora original do Noel Rosa. Fiz uma reconstituição desse filme a partir de relatos de jornais e da música, já que o mesmo pegou fogo em um incêndio na produtora na década de 1950. Além do curso de Jazz que participei em Portugal (tive que sair do curso no último ano), me graduei em Produção Musical pela Anhembi Morumbi e fiz uma pós em Educação Musical pela faculdade Paulista de Artes, todas em São Paulo. Atuo como professor de música no Instituto Federal de Rondônia - IFRO desde 2017. Além das aulas também desenvolvo pesquisas em música e tecnologia, educação musical, comunicação, computação musical e prática musical coletiva. No meu currículo [Lattes](http://lattes.cnpq.br/7456184811841367) é possível ter acesso a todas essas informações acadêmicas de maneira mais detalhada. Se tiver interesse em projetos e pesquisas, pode me enviar um [e-mail](mailto:liperomagna47@hotmail.com) ."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: Data
              url: data/
            - name: Books
              url: books/
            - name: Courses
              url: courses/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/
            - name: Blog
              url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:igelfeld@regensburg.edu
        - name: Zoom
          url: https://www.zoom.us/my/igelfeld
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        - name: GitHub
          url: https://github.com/pmichaillat
        - name: Substack
          url: https://pmichaillat.substack.com
        - name: YouTube
          url: https://www.youtube.com/@pmichaillat
        - name: Twitter
          url: https://x.com/pmichaillat
        - name: Bluesky
          url: https://bsky.app/profile/pmichaillat.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Moritz-Maria von Igelfeld"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2